apiVersion: v1
kind: Service
metadata:
  name: development
  labels:
    app: development
  namespace : ml
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: development